---
- name: Criar usuário
  hosts: centos, ubuntu, redhat
  become: yes  # Para executar com privilégios de superusuário (sudo)

  tasks:
    - name: Criar usuário
      user:
        name: novo_usuario
        comment: "Nome Completo do Usuário"
        password: senha_criptografada  # Use 'mkpasswd --method=sha-512' para gerar a senha criptografada
        state: present

    - name: Adicionar usuário aos grupos
      user:
        name: novo_usuario
        groups: wheel  # Adicione outros grupos se necessário
        append: yes

    - name: Configurar chave SSH para o usuário
      authorized_key:
        user: novo_usuario
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  # Substitua pelo caminho da chave pública do usuário

    # Adicione mais tarefas conforme necessário

